[package]
name = "haydos"
version = "0.1.0"
edition = "2021"
authors = ["Hayden Rinn <hayden@haydenrinn.com>"]

[dependencies]
limine = "0.1"
spin = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
